//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Erg.proto
namespace EasyErgsocket
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Erg")]
  public partial class Erg : global::ProtoBuf.IExtensible
  {
    public Erg() {}
    
    private string _ergId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ergId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ergId
    {
      get { return _ergId; }
      set { _ergId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private EasyErgsocket.ErgType _ergtype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ergtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EasyErgsocket.ErgType ergtype
    {
      get { return _ergtype; }
      set { _ergtype = value; }
    }
    private EasyErgsocket.PlayerType _playertype;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"playertype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EasyErgsocket.PlayerType playertype
    {
      get { return _playertype; }
      set { _playertype = value; }
    }
    private double _distance = default(double);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private double _exerciseTime = default(double);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"exerciseTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double exerciseTime
    {
      get { return _exerciseTime; }
      set { _exerciseTime = value; }
    }
    private uint _cadence = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"cadence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cadence
    {
      get { return _cadence; }
      set { _cadence = value; }
    }
    private uint _paceInSecs = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"paceInSecs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint paceInSecs
    {
      get { return _paceInSecs; }
      set { _paceInSecs = value; }
    }
    private uint _calories = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"calories", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint calories
    {
      get { return _calories; }
      set { _calories = value; }
    }
    private uint _power = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint power
    {
      get { return _power; }
      set { _power = value; }
    }
    private uint _heartrate = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"heartrate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint heartrate
    {
      get { return _heartrate; }
      set { _heartrate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErgType")]
    public enum ErgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROW", Value=0)]
      ROW = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BIKE", Value=1)]
      BIKE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RUN", Value=2)]
      RUN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=3)]
      OTHER = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerType")]
    public enum PlayerType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HUMAN", Value=0)]
      HUMAN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOT", Value=1)]
      BOT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REPLAY", Value=2)]
      REPLAY = 2
    }
  
}